/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9ed60c96-49e7-41d3-9873-4a0a15a54569",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Nv6k0sKMv",
    "aws_user_pools_web_client_id": "4j5rnblbnu5ebl5edbjvtkns4a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7uoue7h5l5b6nluenw64f4srau.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
